"""Global constants shared across the application."""

from typing import Dict, List


RESOURCES = [
    {"name": "brain overment", "url": "brain.overment.com", "scrappable": True},
    {"name": "goodreads.com / books", "url": "www.goodreads.com", "scrappable": True},
    {"name": "Farnam Street Blog", "url": "fs.blog", "scrappable": True},
    {"name": "next.js", "url": "nextjs.org", "scrappable": True},
    {"name": "sveltekit", "url": "kit.svelte.dev", "scrappable": True},
    {"name": "react", "url": "react.dev", "scrappable": True},
    {"name": "vue", "url": "vuejs.org", "scrappable": True},
    {"name": "svelte", "url": "svelte.dev", "scrappable": True},
    {"name": "tailwind css", "url": "tailwindcss.com", "scrappable": True},
    {"name": "css / javascript", "url": "developer.mozilla.org", "scrappable": True},
    {"name": "typescript", "url": "typescriptlang.org", "scrappable": True},
    {"name": "AI / prompt / LLM / AI models / prompt engineering / GPT", "url": "arxiv.org", "scrappable": True},
    {"name": "OpenAI / ChatGPT / AI / GPT-4 / GPT-3.5", "url": "openai.com", "scrappable": True},
    {"name": "Figma", "url": "help.figma.com", "scrappable": True},
    {"name": "GitHub", "url": "github.com", "scrappable": True},
    {"name": "GraphQL", "url": "graphql.org", "scrappable": True},
    {"name": "Docker", "url": "docker.com", "scrappable": True},
    {"name": "Kubernetes", "url": "kubernetes.io", "scrappable": True},
    {"name": "AWS", "url": "aws.amazon.com", "scrappable": True},
    {"name": "Firebase", "url": "firebase.google.com", "scrappable": True},
    {"name": "nginx", "url": "nginx.org", "scrappable": True},
    {"name": "Qdrant", "url": "qdrant.tech", "scrappable": True},
    {"name": "Firecrawl", "url": "firecrawl.com", "scrappable": True},
    {"name": "Swift", "url": "swift.org", "scrappable": True},
    {"name": "DigitalOcean", "url": "digitalocean.com", "scrappable": True},
    {"name": "Rust", "url": "rust-lang.org", "scrappable": True},
    {"name": "Python", "url": "python.org", "scrappable": True},
    {"name": "Node.js", "url": "nodejs.org", "scrappable": True},
    {"name": "Express.js", "url": "expressjs.com", "scrappable": True},
    {"name": "MongoDB", "url": "mongodb.com", "scrappable": True},
    {"name": "PostgreSQL", "url": "postgresql.org", "scrappable": True},
    {"name": "Elasticsearch", "url": "elastic.co", "scrappable": True},
    {"name": "Redis", "url": "redis.io", "scrappable": True},
    {"name": "RabbitMQ", "url": "rabbitmq.com", "scrappable": True},
    {"name": "Git", "url": "git-scm.com", "scrappable": True},
    {"name": "Notion", "url": "notion.so", "scrappable": True},
    {"name": "Make / Integromat", "url": "make.com", "scrappable": True},
    {"name": "Zapier", "url": "zapier.com", "scrappable": True},
    {"name": "Airtable", "url": "airtable.com", "scrappable": True},
    {"name": "Google Sheets", "url": "sheets.google.com", "scrappable": True},
    {"name": "Tauri / Tauri Framework", "url": "https://tauri.app", "scrappable": True},
    {"name": "DrizzleORM", "url": "orm.drizzle.team/", "scrappable": True},
    {"name": "Langchain", "url": "js.langchain.com/docs", "scrappable": True},
    {"name": "Midjourney", "url": "docs.midjourney.com", "scrappable": True},
    {"name": "Vercel", "url": "vercel.com", "scrappable": True},
    {"name": "Netlify", "url": "netlify.com", "scrappable": True},
    {"name": "Youtube", "url": "youtube.com", "scrappable": False},
    {"name": "Wikipedia / Definitions / People / Products / Companies", "url": "wikipedia.org", "scrappable": True},
]
