"""Global constants shared across the application."""

from typing import Dict, List


RESOURCES = [
    {"name": "brain overment", "url": "brain.overment.com"},
    {"name": "goodreads.com / books", "url": "www.goodreads.com"},
    {"name": "Farnam Street Blog", "url": "fs.blog"},
    {"name": "next.js", "url": "nextjs.org"},
    {"name": "sveltekit", "url": "kit.svelte.dev"},
    {"name": "react", "url": "react.dev"},
    {"name": "vue", "url": "vuejs.org"},
    {"name": "svelte", "url": "svelte.dev"},
    {"name": "tailwind css", "url": "tailwindcss.com"},
    {"name": "css / javascript", "url": "developer.mozilla.org"},
    {"name": "typescript", "url": "typescriptlang.org"},
    {"name": "AI / prompt / LLM / AI models / prompt engineering / GPT", "url": "arxiv.org"},
    {"name": "OpenAI / ChatGPT / AI / GPT-4 / GPT-3.5", "url": "openai.com"},
    {"name": "Figma", "url": "help.figma.com"},
    {"name": "GitHub", "url": "github.com"},
    {"name": "GraphQL", "url": "graphql.org"},
    {"name": "Docker", "url": "docker.com"},
    {"name": "Kubernetes", "url": "kubernetes.io"},
    {"name": "AWS", "url": "aws.amazon.com"},
    {"name": "Firebase", "url": "firebase.google.com"},
    {"name": "nginx", "url": "nginx.org"},
    {"name": "Qdrant", "url": "qdrant.tech"},
    {"name": "Firecrawl", "url": "firecrawl.com"},
    {"name": "Swift", "url": "swift.org"},
    {"name": "DigitalOcean", "url": "digitalocean.com"},
    {"name": "Rust", "url": "rust-lang.org"},
    {"name": "Python", "url": "python.org"},
    {"name": "Node.js", "url": "nodejs.org"},
    {"name": "Express.js", "url": "expressjs.com"},
    {"name": "MongoDB", "url": "mongodb.com"},
    {"name": "PostgreSQL", "url": "postgresql.org"},
    {"name": "Elasticsearch", "url": "elastic.co"},
    {"name": "Redis", "url": "redis.io"},
    {"name": "RabbitMQ", "url": "rabbitmq.com"},
    {"name": "Git", "url": "git-scm.com"},
    {"name": "Notion", "url": "notion.so"},
    {"name": "Make / Integromat", "url": "make.com"},
    {"name": "Zapier", "url": "zapier.com"},
    {"name": "Airtable", "url": "airtable.com"},
    {"name": "Google Sheets", "url": "sheets.google.com"},
    {"name": "Tauri / Tauri Framework", "url": "https://tauri.app"},
    {"name": "DrizzleORM", "url": "orm.drizzle.team/"},
    {"name": "Langchain", "url": "js.langchain.com/docs"},
    {"name": "Midjourney", "url": "docs.midjourney.com"},
    {"name": "Vercel", "url": "vercel.com"},
    {"name": "Netlify", "url": "netlify.com"},
    {"name": "Youtube", "url": "youtube.com"},
    {"name": "Wikipedia / Definitions / People / Products / Companies", "url": "wikipedia.org"},
]
